Last loaded image folder: E:/data_chuli/images
Last loaded image name: 0_1755056063_150.jpg
Last loaded label folder: E:/data_chuli/labels
check_ls: null
classes: []
conf: 0.5
filter_conf: 0.85
iou: 0.85
model: "E:/px/yolo_train/dect/runs/detect/2025/\u91CD\u5E86\u8346\u6C5F\u4EBA\u5458\
  +\u5E3D\u5B50/weights/best.pt"
